### User Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ali",
  "password": "password"
}

### User Logout
POST http://localhost:3000/api/logout
Authorization: Bearer <your-jwt-token-here>

#
### get random meme
GET http://localhost:3001/api/random-meme
### get random caption
GET http://localhost:3001/api/caption

### get correct caption by memeid
GET http://localhost:3001/api/correct-caption/1

### get high scores
GET http://localhost:3001/api/leaderboard

### get Userdata by username
GET http://localhost:3001/api/users/ali

### get game history by userId
GET http://localhost:3001/api/users/ali/games

### post session
POST http://localhost:3001/api/sessions
Content-Type: application/json
# Authorization
{
  "username": "ali",
  "password": "password"
}